### ISSUE TITLE
Dynamic versioning for titiler-cmr

### ISSUE THREAD

**Issue by maxrjones** [developmentseed/titiler-cmr#26]
For testing out caching mechanisms, it would be helpful to store the titiler-cmr version in test metadata, including the post-release information. I haven't used [PDM](https://github.com/pdm-project/pdm) for package management before, so I don't fully understand the setup. Does the current strategy require modifying the `__version__` defined in `titiler/cmr/__init__.py` when a new tag is released? If so, would there be support for a modification to instead use [dynamic versioning](https://pdm-project.org/en/latest/reference/pep621/#__tabbed_1_2)?

**Comment by maxrjones** [comment]
cc @abarciauskas-bgse @vincentsarago 

It looks like from a quick search most of the new titiler extensions use `source = "file"` for `tool.pdm.version`, but I couldn't find a repo with multiple tags to understand how subsequent release versions work.

**Comment by vincentsarago** [comment]
every time we make a release in titiler-* module we update the `__version__` variable in the `__init__.py` 

workflow:
- update version in `__init__.py`  (usually using `bump-my-version`
- create tags 

as we never released `titiler-cmr` as an official package we never updated the version nor created tags.

**Comment by maxrjones** [comment]
what's the motivation for using the static versioning? my experience has been that the extra metadata and lack of manual steps in dynamic versioning makes it worthwhile to use

**Comment by vincentsarago** [comment]
I'm not sure to understand 
Right now the titiler-cmr is set to use dynamic version (from the init file)

**Comment by maxrjones** [comment]
> I'm not sure to understand Right now the titiler-cmr is set to use dynamic version (from the init file)

Sorry, I wasn't clear in my original issue. Please see https://github.com/developmentseed/titiler-cmr/pull/27 for the specific proposal, which is to use dynamic versioning based on the git history.

**Comment by hrodmn** [comment]
I believe this was resolved by #27 - closing it out!
