### ISSUE TITLE
Upgrade to use new titiler.xarray (and rio-tiler==7.1.0)

### ISSUE THREAD

**Issue by hrodmn** [developmentseed/titiler-cmr#37]
https://github.com/cogeotiff/rio-tiler/releases/tag/7.1.0

* use the new dynamic reader selection capability
* fix upside down images from `XarrayReader`

**Comment by vincentsarago** [comment]
Sadly you won't be able to update to rio-tiler ~-=7.0 while with titiler~=0.18 :-(

**Comment by hrodmn** [comment]
Thanks for the reminder @vincentsarago, I just filed the issue so I don't forget about why we want to do the upgrade here!

**Comment by vincentsarago** [comment]
ideally you'll update to titiler.xarray==0.19 to get everything you need 😅
